<!DOCTYPE html>
<html>
<head>
    <title>Student Event Schedule</title>
    <style>
        @page { margin: 20px; }
        body {
            font-family: 'Arial', sans-serif;
            font-size: 14px;
            margin: 20px;
            background-color:rgb(255, 255, 255);
            color: #333;
            text-align: center; /* Center all content in the body */
        }

        /* Header Styling */
        .header {
            margin-bottom: 20px;
        }

        .header h2 {
            font-size: 24px;
            font-weight: bold;
            color: #800000; /* UTM color */
        }

        .header h3 {
            margin: 5px 0;
            font-size: 18px;
            font-weight: normal;
            color: #555;
        }

        /* Information section */
        .info {
            background: white;
            padding: 15px;
            margin-bottom: 20px;
            font-size: 16px;
            display: inline-block; /* Center the info section */
            text-align: left; /* Align text to the left */
            width: 50%; /* Adjust width to the left side */
            margin-left: 10px;
            margin-right: auto;
        }

        .info p {
            margin: 5px 0;
            font-weight: bold;
        }

        /* Table Styling */
        .table-container {
            width: 80%;
            margin-top: 20px;
            margin-left: auto;
            margin-right: auto;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
            background: white;
            border-radius: 10px;
            overflow: hidden;
        }

        th, td {
            padding: 12px;
            text-align: center; /* Center the content inside the table */
            font-size: 14px;
        }

        th {
            background-color: #800000;
            color: white;
            font-size: 16px;
        }

        td {
            color: #444;
        }

        tr:nth-child(even) {
            background-color: #f7f7f7;
        }

        tr:hover {
            background-color: #eee;
        }

        /* Footer Styling */
        .footer {
            margin-top: 40px;
            font-size: 12px;
            color: #888;
            border-top: 1px solid #ddd;
            padding-top: 15px;
        }

        .footer p {
            margin: 0;
        }

    </style>
</head>
<body>
   
    <div class="header">
        <h2>UNIVERSITI TEKNOLOGI MALAYSIA</h2>
        <h3>Student Event Schedule</h3>
    </div>

    <div class="info">
        <p>Name: {{ $student_name }}</p>
        <p>Student Matric: {{ $student_matric }}</p>
    </div>

    <div class="table-container">
        <table>
            <thead>
                <tr>
                    <th>No.</th>
                    <th>Event Title</th>
                    <th>Date</th>
                    <th>Location</th>
                </tr>
            </thead>
            <tbody>
                @foreach($events->sortBy('start') as $index => $event)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td><strong>{{ $event->title }}</strong></td>
                        <td>{{ date('D, d M Y', strtotime($event->start)) }}</td>
                        <td>{{ $event->location }}</td>
                    </tr>
                @endforeach
            </tbody>        </table>
    </div>

    <div class="footer">
        <p>Generated by FlowSync System | Universiti Teknologi Malaysia</p>
    </div>

</body>
</html>
